name: publish
on:
  push:
    branches: ["main"]
  workflow_dispatch:

concurrency:
  group: publish-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  id-token: write

env:
  GCP_PROJECT_ID: decent-surf-467802-h9
  GCP_REGION: us-central1
  GAR_REPO: wcct
  API_SERVICE: wcct-api
  UI_SERVICE: wcct-ui
  MPLBACKEND: Agg

jobs:
  test-build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install deps
        run: |
          python -m pip install -U pip
          python -m pip install -r requirements.txt nbclient pytest

      - name: Run notebooks and tests
        run: |
          python scripts/run_all.py
          pytest

      - name: Auth to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/320060026697/locations/global/workloadIdentityPools/github/providers/github-provider
          service_account: gh-actions-deployer@decent-surf-467802-h9.iam.gserviceaccount.com

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Artifact Registry auth
        run: gcloud auth configure-docker $GCP_REGION-docker.pkg.dev -q

      - name: Build and push images
        env:
          API_IMG: ${{ env.GCP_REGION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.GAR_REPO }}/wcct-api:${{ github.sha }}
          UI_IMG: ${{ env.GCP_REGION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.GAR_REPO }}/wcct-ui:${{ github.sha }}
        run: |
          docker build -t "$API_IMG" -f Dockerfile .
          docker build -t "$UI_IMG" -f Dockerfile.ui .
          docker push "$API_IMG"
          docker push "$UI_IMG"
          echo "API_IMG=$API_IMG" >> $GITHUB_ENV
          echo "UI_IMG=$UI_IMG" >> $GITHUB_ENV

      - name: Deploy API
        run: |
          gcloud run deploy "$API_SERVICE" \
            --image "$API_IMG" \
            --project "$GCP_PROJECT_ID" \
            --region "$GCP_REGION" \
            --service-account "wcct-api-sa@${GCP_PROJECT_ID}.iam.gserviceaccount.com" \
            --no-allow-unauthenticated \
            --port 8000 \
            --cpu 1 --memory 1Gi \
            --max-instances 3 --min-instances 1 \
            --timeout 300

      - name: Get API URL
        run: |
          API_URL=$(gcloud run services describe "$API_SERVICE" --project "$GCP_PROJECT_ID" --region "$GCP_REGION" --format='value(status.url)')
          echo "API_URL=$API_URL" >> $GITHUB_ENV

      - name: Deploy UI
        run: |
          gcloud run deploy "$UI_SERVICE" \
            --image "$UI_IMG" \
            --project "$GCP_PROJECT_ID" \
            --region "$GCP_REGION" \
            --service-account "wcct-ui-sa@${GCP_PROJECT_ID}.iam.gserviceaccount.com" \
            --no-allow-unauthenticated \
            --port 8050 \
            --set-env-vars API_BASE="$API_URL",API_AUDIENCE="$API_URL" \
            --cpu 1 --memory 1Gi \
            --max-instances 3 \
            --timeout 300

      - name: Show endpoints
        run: |
          echo "API_URL=$API_URL"
          gcloud run services describe "$UI_SERVICE" --project "$GCP_PROJECT_ID" --region "$GCP_REGION" --format='value(status.url)'
